#!/bin/bash
#
# This script runs the image generated by the docker build script
# using docker run command, where:
#   --rm  automatically removes the container and on exit
#   -i  keeps the standard input open
#   -t  provides a terminal as a interactive shell within container
#   --volumes  are file systems mounted on docker container to preserve
# data generated during the yocto build and these are stored on the host.
# Left side being an absolute path on the host machine, right side being
# an absolute path inside the container.
#
# The script can be run with:
#
#   $ ./docker-run.sh

. env.sh

if [ -d ${DOCKER_WORKDIR} ]; then
        mkdir -pv ${DOCKER_WORKDIR}
fi

# run the docker image
docker run -it --rm \
    --volume ${DOCKER_WORKDIR}:/build \
    --workdir /build \
    "${DOCKER_IMAGE_TAG}"
